server:
  port: 8888

spring:
  datasource:
    username: root
    password: Password@123
    url: jdbc:mysql://111.229.251.142:3306/data?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

#logger Config
logging:
  level:
    com:
      example:
        yangyujiaspringboot: debug

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.yangyjxmspringboot.entity